CREATE TABLE Photos
(
	Id				INTEGER PRIMARY KEY ASC AUTOINCREMENT,
	Thumbnail		BLOB NOT NULL,
	Histogram		BLOB NOT NULL,
	ImageFile		VARCHAR NOT NULL,
	Title			NCHAR,
	Description		VARCHAR,
	Date			DATETIME
);

CREATE TABLE Tags
(
	Id				INTEGER PRIMARY KEY ASC AUTOINCREMENT,
	Name			VARCHAR NOT NULL,
	Description		VARCHAR
);

CREATE TABLE KeyValueMetadata
(
	Id				INTEGER PRIMARY KEY ASC AUTOINCREMENT,
	Key				VARCHAR NOT NULL,
	Value			VARCHAR NOT NULL,
	Photo			INTEGER NOT NULL,

	FOREIGN KEY (Photo) REFERENCES Photos(Id)
);

--Join tables

CREATE TABLE Join_Tags_Photos
(
	Id				INTEGER PRIMARY KEY ASC AUTOINCREMENT,
	Photo			INTEGER NOT NULL,
	Tag				INTEGER NOT NULL,

	FOREIGN KEY (Photo) REFERENCES Photos(Id),
	FOREIGN KEY (Tag)	REFERENCES Tag(Id)
);